// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiG5iFr1afXloYZcShtELDP227lEn5E2c',
    appId: '1:894944926890:web:75219c7b66b20008ca84d3',
    messagingSenderId: '894944926890',
    projectId: 'flutter-chat-c5bd5',
    authDomain: 'flutter-chat-c5bd5.firebaseapp.com',
    storageBucket: 'flutter-chat-c5bd5.appspot.com',
    measurementId: 'G-YNX0T0ZLLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUThHL7miHrYvPf3j5cPbKnm2OWfPzo00',
    appId: '1:894944926890:android:93e41244f2932274ca84d3',
    messagingSenderId: '894944926890',
    projectId: 'flutter-chat-c5bd5',
    storageBucket: 'flutter-chat-c5bd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPb1mo5QJC4gYFHSXhZUyaGP-CdNNy59E',
    appId: '1:894944926890:ios:83317b41ab69d0ecca84d3',
    messagingSenderId: '894944926890',
    projectId: 'flutter-chat-c5bd5',
    storageBucket: 'flutter-chat-c5bd5.appspot.com',
    iosClientId: '894944926890-aps9dho2s8d7677k2miurer9cct2aqad.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPb1mo5QJC4gYFHSXhZUyaGP-CdNNy59E',
    appId: '1:894944926890:ios:83317b41ab69d0ecca84d3',
    messagingSenderId: '894944926890',
    projectId: 'flutter-chat-c5bd5',
    storageBucket: 'flutter-chat-c5bd5.appspot.com',
    iosClientId: '894944926890-aps9dho2s8d7677k2miurer9cct2aqad.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
